#!/usr/bin/python2.7 -tt

import sys
from socket import *

def recv_message(s):
   message = ""
   while True:
     new_msg= s.recv(1024)
     message = message + new_msg
     if message.count("\r\n\r\n") == 1:
       break
  

   return message

def send_message(s,out_message):
	s.send(out_message)  

port= int(sys.argv[1])
s = socket()
s.connect(('localhost', port))
counter = 0
err_message = "HTTP/1.1 404 Not Found\r\nContent-type: text/html\r\nContent-length: 113\r\n\r\n<html><head><title>Not Found</title></head><body>\r\nSorry, the object you requested was not found.\r\n</body></html>\r\n\r\n"
correct_request = "GET /counter HTTP"

while True:
  in_message = recv_message(s)
  request = in_message[:17]
  if request == correct_request:
    counter = counter + 1 
    content = str(counter)
    length = str(len(content))
    out_message = "HTTP/1.0 200 OK\r\nContent-Type: text/html\r\nContent-Length: "+length+"\r\n\r\n"+content+"\r\n\r\n"
    
  else:
    out_message = err_message

  send_message(s,out_message)
  
  

s.close()
