#!/usr/bin/python2.7 -tt
import sys
from socket import *

port= int(sys.argv[1])
print ("port number is:" + str(port))


s = socket()
print("try to connect load-balancer")
s.connect(('localhost', port))
s.send('How are you?')
msg=s.recv(10)
print("-SERVER-recieved message:"+msg)
s.close()
